### ISSUE TITLE
Get Username from Session

### ISSUE THREAD

**Issue by hanymorcos** [Kong/kong-plugin-session#32]
I'm using Basic Auth and session plugin in Kong. I see that the session is only sent to the service. Giving a session how do I get the username?

`plugins:
- name: basic-auth
  service: login-service
  config: 
    hide_credentials: true
- name: session
  service: login-service
  config: 
    secret: opensesame
    cookie_samesite: Lax`
Thanks,

Hany

**Comment by darrenjennings** [comment]
@hanymorcos in which context exactly? If you are writing a plugin, you can access the available data from the context. See code around here:

https://github.com/Kong/kong-plugin-session/blob/ca465471137df879df63242eda5779ca6ac52023/kong/plugins/session/header_filter.lua#L41

like so:
```lua
local kong_session = require "kong.plugins.session.session"

local s = kong.ctx.shared.authenticated_session
if s then
  local consumer_id, credential_id = kong_session.retrieve_session_data(s)
  local consumer, err = kong.cache:get(consumer_cache_key, nil,
                                       kong.client.load_consumer, cid)

  print(consumer.username)
end
```

**Comment by hanymorcos** [comment]
I'm not writing a plugin. The session is being sent to the service but I need the username. I want to know who is authenticated. The backend service is Java Spring Boot.

**Comment by darrenjennings** [comment]
@hanymorcos you should be able to see the consumer headers on your spring boot service, but it will be up to you to return those to other services.

Here's an example response when proxying mockbin.org (`/request` will return the request headers that kong sends to the upstream service):
```
➜  ~ http --session=/tmp/kong :9000/v1/request --auth darrenjennings:kong -v
GET /v1/request HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Basic ZGFycmVuamVubmluZ3M6a29uZw==
Connection: keep-alive
Host: localhost:9000
User-Agent: HTTPie/2.3.0



HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: host,connection,x-forwarded-for,x-forwarded-proto,x-forwarded-host,x-forwarded-port,x-real-ip,x-forwarded-path,x-forwarded-prefix,user-agent,accept-encoding,accept,x-consumer-id,x-consumer-custom-id,x-consumer-username,x-credential-identifier,x-credential-username,x-request-id,via,connect-time,x-request-start,total-route-time
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Fri, 29 Jan 2021 17:38:47 GMT
Etag: W/"4c9-9b4k2KtRoh/mDQiDxZZvA4Dr4Rg"
Kong-Cloud-Request-ID: a8bf6a0bcd6c558640f670bd75431a1f
Server: Cowboy
Set-Cookie: session=LoAkfoUjWpXLdaPPFZjQHQ|1611945527|zQYmoILWi0r38y5_EXE9jutrxf2E_MA6v85YzN5dtjgFciGsDcIDh__bfNGNU7L1vzqnT3ETUySnubJeKv2_UO6QgbtkKftec9yi2OckI_4|uW_o0xyjkJyVN25mbFD9I8tl1Ho; Path=/; SameSite=Strict; Secure; HttpOnly
Transfer-Encoding: chunked
Vary: Accept, Accept-Encoding
Via: kong/2.3.0.0-rc1-enterprise-edition
X-Kong-Proxy-Latency: 1
X-Kong-Upstream-Latency: 208
X-Kong-Upstream-Status: 200
X-Powered-By: mockbin

{
    "bodySize": 0,
    "clientIPAddress": "172.17.0.1",
    "cookies": {},
    "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip, deflate",
        "connect-time": "0",
        "connection": "close",
        "host": "mockbin.org",
        "total-route-time": "0",
        "user-agent": "HTTPie/2.3.0",
        "via": "1.1 vegur",
        "x-consumer-custom-id": "his-custom-id-1234",
        "x-consumer-id": "dfd7fe0f-b64f-47c7-8160-b2b48f11c421",
        "x-consumer-username": "the-username-of-darren",
        "x-credential-identifier": "darrenjennings",
        "x-credential-username": "darrenjennings",
        "x-forwarded-for": "172.17.0.1, 10.102.84.134, 3.133.183.124",
        "x-forwarded-host": "localhost",
        "x-forwarded-path": "/v1/request",
        "x-forwarded-port": "80",
        "x-forwarded-prefix": "/v1",
        "x-forwarded-proto": "http",
        "x-real-ip": "74.132.165.15",
        "x-request-id": "b1f5f093-069b-4c30-a42f-7badcbfdf94c",
        "x-request-start": "1611941927214"
    },
    "headersSize": 725,
    "httpVersion": "HTTP/1.1",
    "method": "GET",
    "postData": {
        "mimeType": "application/octet-stream",
        "params": [],
        "text": ""
    },
    "queryString": {},
    "startedDateTime": "2021-01-29T17:38:47.217Z",
    "url": "http://localhost/request"
}
````

**Comment by hanymorcos** [comment]
Can you share your kong.yaml? It might be that I have bad configuration.

**Comment by hanymorcos** [comment]
Here is what I have? I don't get headers json I only get the token.

```
# ------------------------------------------------------------------------------
# This is an example file to get you started with using
# declarative configuration in Kong.
# ------------------------------------------------------------------------------

# Metadata fields start with an underscore (_)
# Fields that do not start with an underscore represent Kong entities and attributes

# _format_version is mandatory,
# it specifies the minimum version of Kong that supports the format

_format_version: "2.1"

# _transform is optional, defaulting to true.
# It specifies whether schema transformations should be applied when importing this file
# as a rule of thumb, leave this setting to true if you are importing credentials
# with plain passwords, which need to be encrypted/hashed before storing on the database.
# On the other hand, if you are reimporting a database with passwords already encrypted/hashed,
# set it to false.

_transform: true

# Each Kong entity (core entity or custom entity introduced by a plugin)
# can be listed in the top-level as an array of objects:

services:
- name: login-service
  host: service
  port: 3000
  protocol: http
  # Entities can store tags as metadata
  tags:
  - auth
  # Entities that have a foreign-key relationship can be nested:
  routes:
  - name: login
    paths:
    - /
    strip_path: true
- name: header-service
  host: service
  port: 3000
  protocol: http
  # Entities can store tags as metadata
  tags:
  - no-auth
  # Entities that have a foreign-key relationship can be nested:
  routes:
  - name: headers
    paths:
    - /list
    strip_path: true


# routes:
# - name: another-route
#   # Relationships can also be specified between top-level entities,
#   # either by name or by id
#   service: example-service
#   hosts: ["hello.com"]


consumers:
- username: test-user
  basicauth_credentials:
  - username: Aladdin
    password: OpenSesame

# When an entity has multiple foreign-key relationships
# (e.g. a plugin matching on both consumer and service)
# it must be specified as a top-level entity, and not through
# nesting.

# plugins:
# - name: rate-limiting
#   consumer: example-user
#   service: another-service
#   _comment: "example-user is extra limited when using another-service"
#   config:
#     hour: 2
#   # tags are for your organization only and have no meaning for Kong:
#   tags:
#   - extra_limits
#   - my_tag
plugins:
- name: basic-auth
  service: login-service
  config: 
    hide_credentials: true
- name: session
  service: login-service
  config: 
    secret: opensesame
    cookie_samesite: Lax
```
